version: 2.1

jobs:
  build-and-test:
    docker:
      - image: maven:3.9.9-eclipse-temurin-21
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
            - maven-deps-
      - run:
          name: Run tests and generate coverage
          command: mvn verify -DskipITs
      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Upload coverage to Coveralls
          command: mvn coveralls:report -DrepoToken=${COVERALLS_TOKEN}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-report

workflows:
  build-test:
    jobs:
      - build-and-test
